version: '3'

services: 
  v2rc:
    image: "v2fly/v2fly-core"
    volumes: 
      - "./conf:/etc/v2ray"
    logging: 
      driver: json-file
      options:
        max-size: "1m"
    ports:
      - 14280:1080
      - 14281:1081


  
