version: '3'

services: 
  v2r:
    image: "v2fly/v2fly-core"
    volumes: 
      - "./config.json:/etc/v2ray/config.json"
    logging: 
      driver: json-file
      options:
        max-size: "1m"

  cad:
    image: "caddy"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/ssl
    ports: 
      - 在config.json中的端口:443
    logging: 
      driver: json-file
      options:
        max-size: "1m"


  